---

# Setup/install tasks.
- include: ubuntu.yml
  when: dist_type == 'ubuntu'

- include: redhat.yml
  when: dist_type == 'redhat'

- name: install pip modules
  become: true
  pip: name={{ item }} state=present
  with_items:
    - "{{ python_pip_modules }}"
  when: python_pip_modules is defined

