---

- name: include os-specific variables
  include_vars: "{{ dist_type }}.yml"

- name: update apt cache
  become: true
  raw: apt update
  when: dist_type == 'ubuntu'

- name: install packages for debian system
  become: true
  raw: apt install {{ item }} -y
#  apt: name={{ item }} state=present
  with_items:
    - "{{ main_packages }}"
    - "{{ os_packages }}"
    - "{{ python_package_modules }}"
  when: dist_type == 'ubuntu'
